CREATE TABLE IF NOT EXISTS customers(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS TEXT(500) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    DATE_REGISTRATION TIMESTAMP NOT NULL,
    STATUS TINYINT NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'SYSDBA',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'SYSDBA',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_BY VARCHAR(50) NULL,
    DELETED_AT TIMESTAMP NULL,
    PRIMARY KEY(ID)
);
